version: "2.3"

services:

  api:
    build:
      context: .
      dockerfile: kernel/Dockerfile
    image: kernel:latest
    working_dir: /app
    container_name: kernel-api
    command: uvicorn main:app --host 0.0.0.0 --port 8082 --reload
    volumes:
      - ./kernel/main.py:/app/main.py
      - ./kernel/requirements.txt:/app/requirements.txt
      - ./kernel/:/app/
    ports:
      - 5766:8082
    env_file:
      - .env
  data-service:
    build:
      context: .
      dockerfile: data-service/Dockerfile
    image: data-service:v1
    #    entrypoint: "tail -F whatever"
    entrypoint: uvicorn main:app --host 0.0.0.0 --port 9393 --reload
    ports:
      - 9393:9393
    volumes:
      - ./data-service/main.py:/app/main.py
      - ./data-service/requirements.txt:/app/requirements.txt
      - ./data-service/:/app/
    environment:
      DB_URL: mongodb://root:example@mongo-db:27017/
      DB_NAME: jobs_database
    env_file:
      - .env

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    image: worker:v1
    command: "python ./worker.py"
    volumes:
      - ./worker/worker.py:/app/worker.py
      - ./worker/requirements.txt:/app/requirements.txt
    env_file:
      - .env
  performance-test-master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/load_testing.py --master -H http://api:8082
    env_file:
      - .env

  performance-test-worker1:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/load_testing.py --worker --master-host performance-test-master
