apiVersion: v1
kind: Service
metadata:
  name: data-service-service
  namespace: ds-data-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - nodePort: 31235
      port: 8080
      targetPort: 9393