apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ds-frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - nodePort: 31237
      port: 8080
      targetPort: 80