apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ds-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: ds-frontend
          image: 501833808881.dkr.ecr.us-east-1.amazonaws.com/ds-frontend:v1
          ports:
            - containerPort: 80
