apiVersion: v1
kind: Service
metadata:
  name: kernel-service
  namespace: ds-kernel
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - nodePort: 31236
      port: 8080
      targetPort: 8082